task-1 done
semiletkin/omp-bot pull request #1
Opened 2021-10-17 19:13 UTC by semiletkin

Add domain rating with subdomain items
 Add commands delete, get, new, edit, list, help, defualt

2021-10-21 09:19 UTC, Maklayna requested changes

2021-10-21 09:19 UTC, Maklayna commented on internal/service/rating/items/service.go
> +	return 0, errors.New("entity not found")
Все кастомные ошибки лучше перенести в константы

2021-10-21 09:19 UTC, Maklayna commented on internal/app/commands/rating/items/command_delete.go
> +		return
имхо не очень корректно, не уведомить пользователя об ошибке. не только тут но и везде

2021-10-21 09:19 UTC, Maklayna commented on internal/app/commands/rating/items/commander.go
> +	case "help":
на мой взгляд лучше все строки иметь в константах

2021-10-21 09:19 UTC, Maklayna commented on internal/app/commands/rating/items/command_list.go
> +		if err.Error() == "cursor out of index" {
все кастомные ошибки лучше в константы

2021-10-21 09:19 UTC, Maklayna commented on internal/model/rating/models.go
> +type Items struct {
Множественное число кмк тут все же не нужно

2021-10-21 09:19 UTC, Maklayna commented on internal/app/commands/rating/items/command_new.go
> +	entity := rating.Items{Title: args}
кмк командер, не должен создавать обьекты а болжен лишь роутить команды, а само создание должно быть в  Create

2021-10-21 10:09 UTC, semiletkin commented on internal/app/commands/rating/items/command_new.go
> +	entity := rating.Items{Title: args}
Согласен, но в дз, в описании интерфейса {Subdomain}Service ж прописано

Create({domain}.{Subdomain}) (uint64, error),

т.е на вход уже созданный объект подают

2021-10-21 10:15 UTC, semiletkin commented on internal/model/rating/models.go
> +type Items struct {
Руководствовался описанием placeholder из дз, думал subdomain нельзя менять

2021-10-22 17:26 UTC, Maklayna approved these changes

2021-12-01 18:17 UTC, closed without merging